### ISSUE TITLE
git series format adds "1/1" for single patch series

### ISSUE THREAD

**Issue by jahogan** [git-series/git-series#16]
git format-patch will omit the patch number when formatting only a single patch. git series format however does add that "1/1", when IMO it shouldn't bother.

**Comment by joshtriplett** [comment]
Fair enough.  I'd done this intentionally, after debating whether to match this behavior or not.  But since you've requested it, sure.

However, if you don't mind, I'd like to continue emitting "0/1" and "1/1" for a one-patch series that includes a cover letter, rather than just "[PATCH]" for both.  I find it confusing to see cover letters with just "[PATCH]" in the subject.

**Comment by jahogan** [comment]
Well I suppose its quite subjective, and no big deal really if it was intentional.

I probably wouldn't bother with a cover letter for a single patch, so git's behaviour of omitting it even then does seem odd indeed.

**Comment by joshtriplett** [comment]
I don't feel strongly about it; I just liked the consistency.

I've used a cover letter for a single patch before, when I wanted to provide a substantial non-commit-message explanation *before* the patch rather than below the --- line of the patch.

**Comment by jacob-keller** [comment]
> However, if you don't mind, I'd like to continue emitting "0/1" and "1/1" for a one-patch series that includes a cover letter, rather than just "[PATCH]" for both. I find it confusing to see cover letters with just "[PATCH]" in the subject.

Doesn't git already do this if you generate a cover-letter? If not, I'd propose we fix that. I do think 1/1 is redundant and can be removed unless explicitly requested when there is no cover-letter though.

**Comment by joshtriplett** [comment]
@jacob-keller No, before I posted that comment I tested that with git (version 2.9.3) and it didn't include the numbering when formatting a single patch with a cover letter.

**Comment by boucman** [comment]
would it be possible to simply have a way to pass random options from format-patch down the chain, or would that cause problem ?

**Comment by joshtriplett** [comment]
@boucman `git series format` doesn't use `git format-patch`.  However, please feel free to report any option you need and I can add it.

**Comment by joshtriplett** [comment]
Fixed in commit 0d3aa94e96e09660cb8b207cc044a1e466c0671f.
