### ISSUE TITLE
Support --subject-prefix with format

### ISSUE THREAD

**Issue by ajdlinux** [git-series/git-series#21]
I'd like to be able to go:

    git series format --subject-prefix=RFC

and have it spit out an appropriately prefixed set of patches.

**Comment by joshtriplett** [comment]
Applied in dc0e755f7d10e6bc25d39fb23a9af55eea8c6584 via your patch, and 73b627c73683fcea0e5fcfcee480414ebb318d28 additionally handles the case of an empty subject-prefix.  Thanks!
