### ISSUE TITLE
New git series format --subject-prefix="PATCH somename"  using a blank does not work

### ISSUE THREAD

**Issue by knuto** [git-series/git-series#23]
It seems git series is able to escape the quoting but still fails if blank is used, like I have been
using with git format-patch.

**Comment by joshtriplett** [comment]
What happens when you try that?  I tested that case, and it seems to work here:

```text
~/src/git$ git series format --stdout --subject-prefix='PATCH somename' | grep '^Subject:'
Subject: [PATCH somename] format-patch: Add --rfc for the common case of [RFC PATCH]
```

**Comment by knuto** [comment]
Hmm - this is what I get:

git series format --stdout --subject-prefix='PATCH somename' | grep '^Subject:'
error: Found argument 'somename' which wasn't expected, or isn't valid in this context

USAGE:
    git series format --stdout --subject-prefix <Subject-Prefix>

For more information try --help

(with current git-series b5e0bd8e32db0da7005245a3b2ca627df5ca5635)

**Comment by joshtriplett** [comment]
What shell?  Because that looks like what you'd get if you *didn't* quote the argument.

Can you `which git`?  Any chance you've got a script or alias for git that's not handling quoting correctly?

**Comment by knuto** [comment]
Ah oh - you are quite right - my mistake - I forgot I used a wrapper script to get to the 
right location for the build for git-series, sorry!

**Comment by joshtriplett** [comment]
@knuto No problem; thanks for testing.

Personally, I use symlinks for development:
```text
~$ find ~/.local/ -name 'git-series*' -ls
  8389796      0 lrwxrwxrwx   1 josh     josh           38 Jul  5 14:25 /home/josh/.local/share/man/man1/git-series.1 -> /home/josh/src/git-series/git-series.1
  5506785      0 lrwxrwxrwx   1 josh     josh           49 Jul 16 14:25 /home/josh/.local/bin/git-series -> /home/josh/src/git-series/target/debug/git-series
```

**Comment by knuto** [comment]
Thanks, I have changed to use that myself now.
Did the wrapper as a bit of cautioness with the whole rust/cargo toolchain (based on prior experiences with some non-C language toolchains) but it seems the output from rust is just working 
as it should so probably no need for the wrapper.
