### ISSUE TITLE
add support for rename of branch

### ISSUE THREAD

**Issue by silvio** [git-series/git-series#27]
Consider to add possibility to rename a series.

```bash
git series rename ...
```

**Comment by joshtriplett** [comment]
Commit https://github.com/git-series/git-series/commit/c037d05e9aada8a8f6a555aec2250832f0d68bdb adds cp and mv commands to copy and move (rename) a series.  You can run `git series rename source dest` (or `git series mv source dest`) to rename a series.

You can also omit the source to rename the current series.
