### ISSUE TITLE
git-series format emitting hundreds of commits for a 5 patch series

### ISSUE THREAD

**Issue by kergoth** [git-series/git-series#28]
I suspect it's related to changing the commit base due to a rebase -- I'm adopting an existing patch series into git-series, including changes to the series, by doing a reset --hard to each topic branch over time and then git-series commit'ing each, but the base changes too since the different topic branches were rebased over time as well. There are only 5 commits between the current series base and HEAD.

**Comment by joshtriplett** [comment]
Note that `git series format` currently only pays attention to the committed version of the series; it doesn't format the version in the series index or working version.  (I need to add options to do that; see #6.)  Would that explain the issue?

If not, could you please provide a series of commands to reproduce the problem?

**Comment by kergoth** [comment]
Ah, good point. I'll try to repro and see if that was the cause. Thanks.

**Comment by joshtriplett** [comment]
@kergoth Any luck reproducing?

**Comment by kergoth** [comment]
No luck so far, will close and revisit if I run into it again.
