### ISSUE TITLE
git series commit -m with comma in message causes rest of message to be dropped

### ISSUE THREAD

**Issue by jahogan** [git-series/git-series#30]
$ git series commit -a -m "abcdef abcdef, fedcba fedcba"
[test 40fdade4e394] abcdef abcdef

Everything after the comma is dropped.

Doesn't happen without -m (i.e. using an editor to compose commit message)

**Comment by joshtriplett** [comment]
I can reproduce this with the last release.  Commit https://github.com/git-series/git-series/commit/5bf5bbe8556d065b2d4072a0520218d77c36153f fixes this by upgrading to current clap, which fixed that argument parsing bug.

**Comment by joshtriplett** [comment]
Fixed in 0.8.11.
