### ISSUE TITLE
Add leading zeros to the Patch series in the Subject line

### ISSUE THREAD

**Issue by davidker** [git-series/git-series#39]
I just got the following feedback back from gregkh: 

>> 
>> The purpose of this patch is to add style consistency and beautify the
>> entire file.
>> 
>> Grammar:
>> Uppercased beginning of new sentences/paragraphs
>> Missing ' and .
>> Fixed several comments using prefix phrase "as is in" to "as in"
>> Standard Grammar
>> 
>> Comments:
>> Fixed comments to follow the multiline styling
>> All comments are now either same line or above variable/definitions
>> Removed nested slash-star comments
>> Removed a random comment left by accident
>> Aligned star comments
>> 
>> Signed-off-by: Erik Arfvidson <erik.arfvidson@unisys.com>
>> Signed-off-by: David Kershner <david.kershner@unisys.com>
>
>How did you create these emails?  git format-patch should have put a
leading 0 on the [PATCH 1/14], to make it so that things can be sorted
properly and I can apply them in the correct order.
>
>Please fix up and resend this series.
>
>thanks,
>
>greg k-h

I think I found the line, but I'm not sure how to add changes unless I push my own git repo and then pull from that.

**Comment by davidker** [comment]
I think the lines: 

`try!(writeln!(out,` "Subject: [{}{}0/{}] {}\n", subject_patch, ensure_space(&subject_patch), commits.len(), subject));
format!("[{}{}{}/{}] ", subject_patch, ensure_space(&subject_patch), commit_num+1, commits.len())`

Needs to be changed to soemthing like: 

`try!(writeln!(out,` "Subject: [{}{}{0:width$}/{}] {}\n", subject_patch, ensure_space(&subject_patch),width=commits.len()/10, commits.len(), subject));
format!("[{}{}{number:width$}/{}] ", subject_patch, ensure_space(&subject_patch),number=commit_num+1, width=commits.len()/10, commits.len())`

**Comment by joshtriplett** [comment]
Will fix; thanks for the report.

**Comment by joshtriplett** [comment]
Fixed in git-series 0.9.1.
