### ISSUE TITLE
include a brief tutorial

### ISSUE THREAD

**Issue by BurntSushi** [git-series/git-series#4]
Very nice project! I'm really interested in giving it a try, and it would be *super* useful to have a brief tutorial in addition to the command descriptions in the `README`. I think I can kind of understand how to use the tool from the `README`, but if there were a walkthrough that used real data and a specific sequence of commands, that would dramatically increase my confidence that I understand what the tool is doing.

Another thing that might be useful is to describe what each command does. The `README` states, for example, that this reuses existing `git` functionality. If I weren't to use `git series`, how would I re-create the workflow without it? (I don't mean this as a way to work around `git series`, but rather, as a way to understand it in terms of something that I already understand.)

**Comment by joshtriplett** [comment]
Sure, I can add a sample walkthrough of developing a patch series, and then producing v2 of that series based on upstream feedback.

For what the commands do in terms of the underlying git repository, I'd recommend INTERNALS.md, which documents the exact repository format.

**Comment by jacob-keller** [comment]
I agree also, a user driven "this is what I should do" set of commands and examples would be quite helpful. Also, it might be worth mentioning how this works in comparison to something like Stacked Git which is sort of a quilt  ontop of Git implementation that has unfortunately stagnated.

It might be worth describing the differences between a branch-based git-rebase-interactive driven mode vs the use of git-series. I think git-series promotes using rebase interactive models of local development in a way that actually makes tracking history between versions clean.

I am hoping to be able to experiment with it Soon(TM), and might be able to provide more detailed thoughts on transitioning from branches into using git-series.

**Comment by joshtriplett** [comment]
Fixed in commit 0ae82c2cf90053be45ce68f84552e120ff1df238.  Thanks for the suggestions!
