### ISSUE TITLE
Initialise new series with an empty commit

### ISSUE THREAD

**Issue by asayers** [git-series/git-series#44]
What if `git-series` initialised all new series with an "initial" commit? Ie. one with no parents, the empty tree, and some default message. This gives us the property that the series commit is always the second parent.

The purpose is to make "git-series/" branches a bit easier to work with when `git-series` isn't installed. For instance, you could do a pretty decent imitation of `git series log` with `git log --merges --first-parent git-series/<series>`.

Is it too late for this?

**Comment by joshtriplett** [comment]
@asayers git-series supports series commits that have multiple series-commit parents, as well, to allow for series merges.  So, git-series always has to handle the more general case, at which point handling the "zero series-commit parents" case seems easy enough.

I do think in some cases it may make sense for `git series start` to make a commit, such as if you supply an initial base for the series.  I might add an option to `git series start` to make a commit with a standard message like "Initial series commit".  However, I still wouldn't want to make that commit have zero parents and treat it as a placeholder; among other things, that breaks a different simplifying assumption, namely that a series always has a `series` entry pointing to a commit.

Instead, it's highly likely that in the near-term future, git itself will get support for tracking series commits in a way that makes the "extra parent" hack unnecessary.  There's discussion about this on the git mailing list, and I plan to implement the resulting consensus from that discussion: a new "gitref" object that acts like a gitlink but also requires reachability.

**Comment by asayers** [comment]
> a new "gitref" object that acts like a gitlink but also requires reachability [...] makes the "extra parent" hack unnecessary

Yes, that's a better solution. I assumed this kind of thing was off the table, because of the new tree format it requires, but I see in the mailing-list thread that people are ok with it. Nice!

(For reference: [the thread Josh mentioned][1].)

[1]: http://marc.info/?l=git&m=147828223701858&w=2

**Comment by joshtriplett** [comment]
I'd suggest the [public-inbox archive](https://public-inbox.org/git/20161113175058.t7s4o7h5chqzazb6@upsilon.cc/T/#m49aa2f68015986f677d8077b677a67c5c5beac37); I find it easier to read.

And yeah, I'd made the same assumption. That thread grew out of a great conversation at Linux Plumbers Conference with Junio.
