### ISSUE TITLE
Request: mention git-range-diff(1)

### ISSUE THREAD

**Issue by LemmingAvalanche** [git-series/git-series#66]
The git(1) suite now has the [git-range-diff(1)](https://git-scm.com/docs/git-range-diff) command:

> DESCRIPTION

> This command shows the differences between two versions of a patch series, or more generally, two commit ranges (ignoring merge commits).

([Since Git 2.19.0](https://github.blog/2018-09-10-highlights-from-git-2-19/))

It might be nice to mention this in the readme or somewhere else.

EDIT: More of a _suggestion_ than a _request_, really.

**Comment by joshtriplett** [comment]
Sorry for missing this. Done in https://github.com/git-series/git-series/commit/df971f9f4994ac5ba127600ec6a12e1477d9de3c
