### ISSUE TITLE
git series base and rebase don't accept tags

### ISSUE THREAD

**Issue by jahogan** [git-series/git-series#8]
git series base and git series rebase unobviously refuse to accept tag names, e.g.

$ git series base v4.8-rc1
[3/-1] Object is no commit object

$ git series base 29b4817d4018
Previous base was ...
Set patch series base to 29b4817d4018 Linux 4.8-rc1

and for rebase:

$ git series rebase v4.8-rc1
[3/-3] The requested type does not match the type in ODB

$ git series rebase 29b4817d4018
Checking out files: 11433/11433
Executing: git series base 29b4817d4018df78086157ea3a55c1d9424a7cfc
Previous base was ...
Set patch series base to 29b4817d4018 Linux 4.8-rc1
Successfully rebased and updated detached HEAD.

**Comment by joshtriplett** [comment]
Definitely a bug.  I called `revparse_single` on the passed name, but then I need to peel it to a commit.

**Comment by joshtriplett** [comment]
Fixed in 8cc4318beb482a42a9fd84646f19624ad1a41863
